'use client'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './assets/lib/font-awesome/css/font-awesome.css';
import './assets/lib/Ionicons/css/ionicons.css';
import './assets/css/slim.css';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: '3d model App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <title>{process.env.NEXT_PUBLIC_APP_NAME}</title>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
