# Generated by Django 4.2.7 on 2023-11-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Star', 'Star'), ('Collector', 'Collector'), ('Pionneer', 'Pionneer')], max_length=225, unique=True)),
                ('description', models.TextField(blank=True)),
                ('img_url', models.CharField(blank=True, max_length=225)),
            ],
        ),
    ]
