# Generated by Django 4.2.7 on 2023-11-03 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model3d', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model3d.model3d')),
            ],
        ),
    ]
