# Generated by Django 4.2.7 on 2023-11-03 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=225, unique=True)),
                ('email', models.EmailField(max_length=225, unique=True)),
                ('password', models.CharField(default='', max_length=225)),
                ('profil_img_url', models.CharField(blank=True, max_length=225, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 11, 3, 16, 29, 31, 574566, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
